{{- if .Values.app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kph.fullname" . }}
  labels:
    {{- include "kph.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
{{- end }}
