apiVersion: v1
kind: Secret
metadata:
  name: kph-agent-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kph-agent
type: Opaque
stringData:
  cluster-id: {{ .Values.agent.clusterId | quote }}
  cluster-name: {{ .Values.agent.clusterName | quote }}
  organization-id: {{ .Values.agent.organizationId | quote }}
  api-token: {{ .Values.agent.token | quote }}
  saas-endpoint: {{ .Values.agent.serverUrl | quote }}
